### ISSUE TITLE
flusmic with prismic-javascript features

### ISSUE THREAD

**Issue by gtsopour** [PixelaGt/flusmic#1]
Hello flusmic team,
it is possible to implement with flusmic the Predicates like in prismic-javascript and/or the RichText, Link from 'prismic-dom' and/or the fetchLinks option (add options in the query)?

`
Prismic.getApi(apiEndpoint).then(function(api) {
  return api.query(
      [
        Prismic.Predicates.at('document.type', '{TYPE}'),
        Prismic.Predicates.at('my.{TYPE}.{PROPERTY}', '{PROPERTY_ID}')
      ]
  ); // An empty query will return all the documents
}).then(function(response) {
}, function(err) {
});
`

`
let options = { fetchLinks : ['{PROPERTY_1}', '{PROPERTY_2}']};
Prismic.getApi(apiEndpoint).then(function(api) {
return api.getByID('{ID}', options);
}).then(function(response) {
console.log(response);
console.log(RichText.asText(response.data.title));
}, function(err) {
console.log(err);
});
`

**Comment by pblinux** [comment]
Hey @gtsopour sorry for this (super) late response.

I think it's possible. To be honest, I've hadn't so much time to improve the package but I think include predicates will be much easier to use flusmic. I will work on this.

Thanks.

**Comment by pblinux** [comment]
v1.0.1 release adds querying with predicates (including fetchLinks). :fireworks:
