### ISSUE TITLE
orderings

### ISSUE THREAD

**Issue by mike-app-vise** [PixelaGt/flusmic#13]
I have a problem with the orderings, 
I need to access the document.first_publication_date to order the response from Prismic.
The problem is that it's hardcoded to use the my annotation. 
is it possible to remove the "my" annotation in the:

`String _generateOrdering(Ordering ordering) {
    final descending = ordering.descending ? ' des' : '';
    return 'my.${ordering.customType}.${ordering.field}$descending';
  }`

my belief is that the ordering will be more dynamic this way, also the code uses _des_ for descending, but Prismic uses _desc_ 

but it could be that I'm overlooking something? 

with kind regards.

**Comment by pblinux** [comment]
Hello @mike-app-vise, sorry for the late reply.

Thank you for pointing the 'des' issue, I will fix it.

I will separate the way orderings are generating since there are some that do need 'my' and other not. Thanks for opening the issue.

Regards.

**Comment by nlanatta** [comment]
> Hello @mike-app-vise, sorry for the late reply.
> 
> Thank you for pointing the 'des' issue, I will fix it.
> 
> I will separate the way orderings are generating since there are some that do need 'my' and other not. Thanks for opening the issue.
> 
> Regards.

@pblinux , any update of this issue, can at least put a hotfix with the "d" in the "des" issue, as a work around?

**Comment by pblinux** [comment]
Hi @nlanatta!

Sorry for the delay. Yes, I'm working on a small fix, it will be ready tomorrow.
I'll be updating some other parts and dependencies too. :smile: 

Thanks for the contribution.
