### ISSUE TITLE
Dio error might not have reponse, not handled so it crash

### ISSUE THREAD

**Issue by jaumard** [PixelaGt/flusmic#17]
Code who is crashing:
https://github.com/PixelaGt/flusmic/blob/master/packages/flusmic/lib/src/flusmic_error.dart#L25

Called for example here:
https://github.com/PixelaGt/flusmic/blob/master/packages/flusmic/lib/src/flusmic_repository.dart#L82

From dio's documentation:
https://pub.dev/packages/dio#handling-errors

Errors will have response only for type `RESPONSE`, all other type have response to null.

Should be handled correctly.

Sorry no time for doing a PR even if it's a small one.

**Comment by pblinux** [comment]
Hi @jaumard, thanks for reporting this.

Yep, I need to improve the error handling, I will be working next weekend to solve it.

Thanks again :smile:

**Comment by jaumard** [comment]
It can be reproduce quite easily on my case, just using it without network will trigger the crash.

**Comment by jaumard** [comment]
Any news on that ? :)

**Comment by pblinux** [comment]
Sorry @jaumard, been a little busy the last few days.
I have been checking on this and actually, in the case where there is no connection, `dio` handles this exception so a `FlusmicError` will throw without issues. The only extra case I found was bad deserialization, but I will check again to be sure.

Hope to release the `3.0.0` within 2 weeks with this fixed. :smile:

**Comment by jaumard** [comment]
You're right I didn't re check the code and now it's indeed good :) I'm steel using 2.1.0 as I'm not null safety ready that's why I still have it lol

**Comment by pblinux** [comment]
Great @jaumard!
We are working on improving the `flusmic_ui` package too, so `3.0.0` will include many updates.

Thank you so much for your feedback, I will mark this as solved when the next version is released.

**Comment by jaumard** [comment]
Sorry, I checked again the link I shared to your code lool but you'll get the same error with your fix :) response of a DioError can be null so `response.statusCode` will still crash ( sorry can't relly test 3.0.0 right now )

**Comment by pblinux** [comment]
Hey @jaumard! sorry for disappearing, been a little busy but I'm back 😄 

Yes, you are right, the response from DioError can be null. I'll be releasing the `3.0.0` version with this fixed in the next few days.

Thank you very much for your contribution.
