### ISSUE TITLE
Flutter web support

### ISSUE THREAD

**Issue by emmett-deen** [PixelaGt/flusmic#18]
**Is your feature request related to a problem? Please describe.**
Currently, this package does not list flutter web support on pub.dev I am wondering if that is on the roadmap to be included / why it is not currently.

**Describe the solution you'd like**
Full support for all platforms

**Comment by pblinux** [comment]
Hi @emmett-deen 

Thank you for creating this issue. I'm currently working on improving flusmic_ui, including remove dependencies that are not letting the package be available to use it at web.

I will be fixing this in the next weeks 😁

Thank you again.

**Comment by emmett-deen** [comment]
@pblinux I just tried adding it to see if there were any issues in my flutter-web project and everything seemed to work fine! I am planning on using prismic a good bit with flutter moving forward so if you need any help implementing the next feature set of links, spans, and lists just lmk and I can try to spend some time on it! Thank you for maintaining this project!

**Comment by pblinux** [comment]
Awesome @emmett-deen, thank you! flusmic_ui is using `cached_network_image` for image loading but I'm thinking of moving this to a simple `Image` widget to fully support web. If you have any suggestion or idea to add the full support of rich text I will appreciate it, working on this to be added in v3.0.0 besides other things :wink:

Thank you very much again :smile:
