### ISSUE TITLE
Accessing private API

### ISSUE THREAD

**Issue by Maxim-Filimonov** [PixelaGt/flusmic#5]
Hi,
We don't want to make our API public. Is there a way to pass access token? Don't see it in the docs.

**Comment by pblinux** [comment]
Hi @Maxim-Filimonov 

The authToken param is not integrated yet. We will make an update including it within the next few days. :+1:

**Comment by pblinux** [comment]
Hi @Maxim-Filimonov 

v1.2.0 now includes authToken.
